nodeLinker: node-modules
enableGlobalCache: false

workspaces:
  - apps/*
  - packages/*

packageExtensions:
  "@event-mingle/database@*":
    peerDependencies:
      "@event-mingle/shared": "*"
  "@event-mingle/shared@*":
    peerDependencies:
      "@event-mingle/config": "*"
  "@event-mingle/ui@*":
    peerDependencies:
      "@event-mingle/shared": "*"
      "@event-mingle/config": "*" 